name: jainquest
description: Gamified Jain learning for teens - calm, modern, non-preachy.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  flutter_riverpod: 
  riverpod_annotation: 
  
  # Remote Storage
  
  # Animations
  lottie: 
  confetti: 
  flutter_animate: 
  
  # Notifications
  flutter_local_notifications: 
  timezone: 
  
  # UI Components
  google_fonts:
  flutter_svg: 
  cached_network_image: 
  shimmer: 
  
  # Charts & Analytics
  fl_chart: ^0.70.2 
  
  # Effects
  blur: 
  
  # Haptics & Feedback
  vibration: 
  
  # Sharing
  share_plus:

  video_player: 
  
  # Utilities
  intl: 
  translator: ^1.0.3+1
  equatable: 
  uuid: 
  google_generative_ai: 

  #firebase
  firebase_core:
  cloud_firestore:
  firebase_auth:
  google_sign_in: ^6.2.1
  tutorial_coach_mark: ^1.2.9
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/content/
    - assets/images/
    - assets/videos/
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
