name: jainquest
description: Gamified Jain learning for teens - calm, modern, non-preachy.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Remote Storage
  
  # Animations
  lottie: ^3.0.0
  confetti: ^0.7.0
  flutter_animate: ^4.3.0
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  
  # UI Components
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Charts & Analytics
  fl_chart: ^0.66.0
  
  # Effects
  blur: ^3.0.0
  
  # Haptics & Feedback
  vibration: ^1.8.4
  
  # Sharing
  share_plus: ^7.2.1
  
  # Video/External Links
  url_launcher: ^6.2.2
  video_player: ^2.8.2
  
  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.5
  uuid: ^4.2.2
  google_generative_ai: ^0.4.6

  #firebase
  firebase_core:
  cloud_firestore:
  firebase_auth:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/content/
    - assets/images/
    - assets/videos/
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
