// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ6pgZCDLftBHSsY1G4In5WXTHz7Bv2Eg',
    appId: '1:753911767862:web:8ba20aabba6a0cc060c997',
    messagingSenderId: '753911767862',
    projectId: 'jainquest-4297e',
    authDomain: 'jainquest-4297e.firebaseapp.com',
    storageBucket: 'jainquest-4297e.firebasestorage.app',
    measurementId: 'G-FFCBCSZ2XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_18HqYBKjb-C12bZHLXNL2T1sLMKZ7nM',
    appId: '1:753911767862:android:b4c251908313391060c997',
    messagingSenderId: '753911767862',
    projectId: 'jainquest-4297e',
    storageBucket: 'jainquest-4297e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQhp5k0PDtTfDxrTs787j82JaCE6tAgl8',
    appId: '1:753911767862:ios:baf9f0220590406260c997',
    messagingSenderId: '753911767862',
    projectId: 'jainquest-4297e',
    storageBucket: 'jainquest-4297e.firebasestorage.app',
    iosBundleId: 'com.jainquest.jainquest',
  );
}
